#!/bin/bash
# ----------------------------------------------------------------------------------------
# Desktop Installer
# ----------------------------------------------------------------------------------------
# author:     Mrazek Ales
#             https://github.com/mrazekales
#
# project:    https://github.com/mrazekales/myarch-installer
#
# license:    LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
#
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# GLOBAL STRINGS
# ----------------------------------------------------------------------------------------
apptitle="myArch-installer(Desktop Environment) - Version: 0.1 (LGPLv3)"

txtpressanykey="Press any key to continue."
txtexit="Exit"
txtback="Back"
txtignore="Ignore"
txtoptional="(Optional)"
txtdone="Done"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# MAIN MENU
# ----------------------------------------------------------------------------------------
main_menu(){
  # whiptail strings
  txtmainmenutitle="Main Menu"
  txtaurhelper="AUR helper/base-devel"
  txtdisplaymanager="Display Manager"
  txtdesktopenvironment="Desktop Environment"
  txtpowermanager="Power Manager"
  txtnetworkmanager="Network Manager"
  txtswapfile="Create Swap File"

  txtreboot="Reboot"

  if [ "$1" = "" ]; then
    nextitem="."
  else
    nextitem=$1
  fi
  options=()
  options+=("AUR helper" "")
  options+=("Display Manager" "")
  options+=("Desktop Environment" "")
  options+=("" "")
  options+=("Power Manager" "")
  options+=("Network Manager" "")
  options+=("Swapfile" "")
  sel=$(whiptail --backtitle "$apptitle" --title "$txtmainmenutitle" --menu "" --cancel-button "$txtexit" --default-item "$nextitem" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    case $sel in
      "AUR helper")
      install_yay
        nextitem="AUR helper"
      ;;
      "Display Manager")
        nextitem="Display Manager"
      ;;
      "Desktop Environment")
        nextitem="Desktop Environment"
      ;;
      "Power Manager")
        nextitem="Power Manager"
      ;;
      "Network Manager")
        nextitem="Network Manager"
      ;;
      "Swapfile")
        create_swapfile
        nextitem="Swapfile"
      ;;
    esac
    main_menu "$nextitem"
  else
    clear
  fi
}
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# BASE_DEV/AUR HELPER -YAY
# ----------------------------------------------------------------------------------------
install_yay(){
  echo "Installing 'base-devel'"
  yes | pacman -S base-devel
  
  echo "Installing git"
  yes | pacman -S git
  
  
  users_list=(`cat /etc/passwd | grep "/home" | cut -d: -f1`);
  echo "@user_list"
  pressanykey
  
  clear
  options=()
  options+=("Create new user" "")
  options+=("" "")
  for user in $user_list; do
    options+=("$user" "")
  done
  seluser=$(whiptail --backtitle "$apptitle" --title "Choose user" --menu "User must have SUDO privileges" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [[ $seluser == "Create new user" ]]; then
    seluser=$(whiptail --backtitle "$apptitle" --title "$txtcreatenewuser" --inputbox "" 0 0 "newhomeuser" 3>&1 1>&2 2>&3)
    create_new_user $seluser  
  fi
  install_yay_as $seluser
  pressanykey
}

install_yay_as(){
  clear
  su - $1 
  echo "git clone https://aur.archlinux.org/yay.git"
  git clone https://aur.archlinux.org/yay.git
  echo "cd yay"
  cd yay
  echo "makepkg -si"
  makepkg -si
  echo "cd .."
  cd ..
  echo "rm -r yay"
  rm -r yay
  echo "$txtdone" 
  pressanykey
  su - root
}

create_new_user(){
  clear
  if $1; then    
    echo "useradd -m -s /bin/bash $1"
    useradd -m -s /bin/bash $1
    echo "usermod -aG wheel,storage,audio,video,power $1"
    usermod -aG wheel,storage,audio,video,power $1
    echo "passwd $1"
    passwd $1

    pressanykey

    echo "Setting up SUDO"

    yes | pacman -S sudo
    echo "Creating sudoers.backup"
    cp -v /etc/sudoers /etc/sudoers.backup
    echo "Uncommenting %wheel ALL=(ALL) ALL"
    sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
    echo "'Defaults rootpw' >> /etc/sudoers"
    echo 'Defaults rootpw' >> /etc/sudoers
    #echo 'Defaults targetpw' >> /etc/sudoers 
  fi
  pressanykey
}

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# SWAP FILE
# ----------------------------------------------------------------------------------------
create_swapfile(){

  if [ -e /swapfile ]; then
    echo "Removing old swapfile ..."
    remove_swapfile
  fi

  ramsize=$(cat /proc/meminfo | grep MemTotal | awk '{ print $2 }')
  echo "RAM: $ramsize B"

  if (( $ramsize >= 9000 )); then
    swapsize=$(($ramsize/2000))"M"
  elif (( $ramsize >= 3000 )); then
    swapsize=$(($ramsize/1000))"M"
  else
    swapsize=$(($ramsize/500))"M"
  fi
  clear
  echo "SWAP FILE: $swapsize M"
  echo "fallocate -l ${swapsize//%1/M} /swapfile"
  fallocate -l ${swapsize//%1/M} /swapfile
  echo "chmod 600 /swapfile"
  chmod 600 /swapfile
  echo "mkswap /swapfile"
  mkswap /swapfile
  echo "swapon /swapfile"
  swapon /swapfile
  echo "'/swapfile none swap defaults 0 0' >> /etc/fstab"
  echo "/swapfile none swap defaults 0 0" >> /etc/fstab
  pressanykey
}

remove_swapfile(){
  echo "swapoff -a"
  swapoff -a
  echo "rm -f /swapfile"
  rm -f /swapfile
  echo "sed -i '/pattern to match/d' ./etc/fstab"
  sed -i '//swapfile none swap defaults 0 0/d' ./etc/fstab
  pressanykey
}

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# POWER MANAGER
# ----------------------------------------------------------------------------------------
#power_menu(){}

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# NETWORK MANAGERS
# ----------------------------------------------------------------------------------------
#network_menu(){}

install_networkmanager(){
  echo "Installing networkmanager network-manager-applet"
  yes | pacman -S networkmanager nm-applet 

  echo "Disable dhcpcd and netctl"
  systemctl disable dhcpcd
  systemctl disable netctl-auto

# Using GNOME Keyring
  yes | pacman -S  gnome-keyring libsecret 

  echo "systemctl enable NetworkManager.service"
  systemctl enable NetworkManager.service
  systemctl start NetworkManager.service
  pressanykey
}

install_nftables(){
  echo "Installing nftables < y"
  yes | pacman -S nftables
  echo "systemctl enable nftables.service"
  systemctl enable nftables.service

  echo "Default ruleset"
  nft list ruleset
  nft list ruleset > /etc/nftables.conf
}

install_connman(){
  echo "Installing connman wpa_supplicant bluez openvpn"
  yes | pacman -S connman wpa_supplicant openvpn cmst 

  install_bluez

  echo "Disable dhcpcd and netctl"
  systemctl disable dhcpcd
  systemctl disable netctl-auto

  systemctl enable connman.service
  systemctl start connman.service
  pressanykey
}

install_bluez(){
  echo "Installing bluez bluez-utils"
  yes | pacman -S bluez bluez-utils 
  pressanykey
}

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# GLOBAL FUNCTIONS
# ----------------------------------------------------------------------------------------
choose_editor(){
  options=()
  options+=("nano" "")
  options+=("vim" "")
  options+=("vi" "")
  options+=("edit" "")
  sel=$(whiptail --backtitle "$apptitle" --title "$txteditor" --menu "" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    EDITOR=$sel
  fi
}

pressanykey(){
  read -n1 -p "$txtpressanykey"
}

rebootpc(){
  if (whiptail --backtitle "$apptitle" --title "$txtreboot" --yesno "$txtreboot ?" --defaultno 0 0) then
    clear
    reboot
  fi
}

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# START OF THE PROGRAM
# ----------------------------------------------------------------------------------------

# main menu start
echo "git libnew will be installed"
pressanykey

yes | pacman -S git libnewt

main_menu
exit 0

# --------------------------------------------------------
