#!/bin/bash
# ----------------------------------------------------------------------------------------
#            ENGLISH STRINGS
#           Desktop/App Installer
# ----------------------------------------------------------------------------------------
# author:     Mrazek Ales
#             https://github.com/mrazekales
#
# project:    https://github.com/mrazekales/myarch-installer
#
# license:    LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Global Strings
# ----------------------------------------------------------------------------------------
txtexit="Exit"
txtback="Back"
txtignore="Ignore"
txtpressanykey="Press any key to continue."

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Main Menu
# ----------------------------------------------------------------------------------------
txtmainmenutitle="Main Menu"
txtdisplaymanager="Install Display Manager"
txtdesktopenvironmentr="Install Desktop Environment"
txtnetworkmanager="Install Network Manager"


txtmakepartitions="Disk Partitioning  "
txtkeymap="Keymap"
txtlanguage="Language"
txtreboot="Reboot"

txtrmdone="(optional)"
