#!/bin/bash
# ----------------------------------------------------------------------------------------
#             ENGLISH STRINGS
#           Arch Linux Installer
# ----------------------------------------------------------------------------------------
# author:     Mrazek Ales
#             https://github.com/mrazekales
#
# project:    https://github.com/mrazekales/myarch-desktop
#
# license:    LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
# ----------------------------------------------------------------------------------------
