#!/bin/bash
# ----------------------------------------------------------------------------------------
#             ENGLISH STRINGS
#           Arch Linux Installer
# ----------------------------------------------------------------------------------------
# author:     Mrazek Ales
#             https://github.com/mrazekales
#
# project:    https://github.com/mrazekales/myarch-installer
#
# license:    LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Global Strings
# ----------------------------------------------------------------------------------------
locale=en_US.UTF-8
usingkeymap=us

txtexit="Exit"
txtback="Back"
txtignore="Ignore"
txtpressanykey="Press any key to continue."

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Main Menu
# ----------------------------------------------------------------------------------------
txtmainmenutitle="Main Menu"
txtrankmirrors="Rank Mirrors"
txtmakepartitions="Disk Partitioning  "
txtselectpartitions="Partitions Selection  "
txtformatpartitions="Partitions Formating  "
txtmount="Mount and Install"
txtkeymap="Keymap"
txtlanguage="Language"
txtreboot="Reboot"

txtrmdone="(optional)"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Disk Partitioning/Formating
# ----------------------------------------------------------------------------------------
# partitioning
txtpartitionmenu="Partition Menu"
txtautoparts="Automatic Partitioning"
txteditparts="Manual Partitioning"

txtautopartsconfirm="Selected device : %1\n\nAll data will be erased ! \n\nContinue ?"

txtautopartclear="Clear all partition data"
txtautopartcreate="Create %1 partition"
txthybridpartcreate="Set hybrid MBR"
txtautopartsettype="Set %1 partition type"

# select partitions
txtselectpartsmenu="Select Partitions Menu"
txtselectdevice="Select %1 device :"
txtselecteddevices="Selected devices :"

# formating
txtformatconfirm="Warning, all data on selected devices will be erased ! \nFormat devices ?"

txtformatpartition="Format Partition"


txtselectformat="Select partition format for %1 :"
txtformating="Formatting partition %1 as"
txtcreateluksdevice="Create luks device :"
txtopenluksdevice="Open luks device :"
txtluksdevicecreated="luks device created !"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Arch Installation Menu
# ----------------------------------------------------------------------------------------
txtinstallmenu="Install Menu"
txtinstallarchlinux="Install Arch Linux   "
txtbootloader="Install Bootloader"
txtconfigarchlinux="Config Arch Linux"
txtunmount="Unmount"

txtarchinstallmenu="Arch Install Menu"
txtbasedev="Install Devel Packages"
txtinstalldev="Do you want to install 'base-dev' packages?"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Bootloader Menu
# ----------------------------------------------------------------------------------------
txtbootloadermenu="Choose your bootloader"

txtefibootmgr="efibootmgr is required for EFI computers."

txtbootloadergrubmenu="Grub Install Menu"
txtrungrubmakeconfig="Run grub-mkconfig ?"
txtgrubluksdetected="Encrypted root partion !\n\nAdd cryptdevice= to GRUB_CMDLINE_LINUX in /etc/default/grub ?"

txtbootloadersyslinuxmenu="Syslinux Install Menu"
txtsyslinuxaddefibootmgr="EFI install require efibootmgr"
txtsyslinuxaddgptfdisk="GPT disk require gptfdisk"
txtsyslinuxaddmtools="FAT boot part require mtools"

txtbootloaderrefindmenu="rEFInd Install Menu"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Config Menu
# ----------------------------------------------------------------------------------------
txtconfmenu="Config Menu"
txtsethostname="Set Computer Name"
txtsetkeymap="Set Keymap"
txtsetfont="Set Font"
txtsetlocale="Set Locale"
txtsettime="Set Time"
txtsetrootpassword="Set root password"
txtcreatenewuser="Create home user"

txtuseutcclock="Use UTC hardware clock ?"

txtoptional="Optional"
txtrecommandeasyinst="Recommanded for easy install"
txtset="Set %1"
txtgenerate="Generate %1"
txtedit="Edit %1"
txtinstall="Install %1"
txtenable="Enable %1"

