#!/bin/bash
# ----------------------------------------------------------------------------------------
#             ENGLISH STRINGS
#           Arch Linux Installer
# ----------------------------------------------------------------------------------------
# author:     Mrazek Ales
#             https://github.com/mrazekales
#
# project:    https://github.com/mrazekales/myarch-installer
#
# license:    LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Global Strings
# ----------------------------------------------------------------------------------------
locale=en_US.UTF-8
usingkeymap=us

txtexit="Exit"
txtback="Back"
txtignore="Ignore"
txtpressanykey="Press any key to continue."

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Main Menu
# ----------------------------------------------------------------------------------------
txtmainmenutitle="Main Menu"
txtrankmirrors="Rank Mirrors"
txtmakepartitions="    Partitioning"
txtselectpartitions="    Selection"
txtformatpartitions="    Formating"
txtmount="Mount and Install"
txtkeymap="Keymap"
txtlanguage="Language"
txtreboot="                 Reboot"

txtrmdone="(optional)"
txtmpdone=""
txtspdone=""
txtfpdone=""
txtmountdone=""

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Disk Partitioning/Formating
# ----------------------------------------------------------------------------------------
# partitioning
txtpartitionmenu="Partition Menu"
txtautoparts="Automatic Partitioning"
txteditparts="Manual Partitioning"

txtautopartsconfirm="Selected device : %1\n\nAll data will be erased ! \n\nContinue ?"

txtautopartclear="Clear all partition data"
txtautopartcreate="Create %1 partition"
txthybridpartcreate="Set hybrid MBR"
txtautopartsettype="Set %1 partition type"

# select partitions
txtselectpartsmenu="Select Partitions Menu"
txtselectdevice="Select %1 device :"
txtselecteddevices="Selected devices :"

# formating
txtformatconfirm="Warning, all data on selected devices will be erased ! \nFormat devices ?"

txtformatpartitions="Format Partitions"
txtformatpartition="Format Partition"


txtselectformat="Select partition format for %1 :"
txtformating="Formatting partition %1 as"
txtcreateluksdevice="Create luks device :"
txtopenluksdevice="Open luks device :"
txtluksdevicecreated="luks device created !"

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Arch Installation Menu
# ----------------------------------------------------------------------------------------




txtunmount="Unmount"



txtinstallmenu="Install Menu"

txtarchinstallmenu="Arch Install Menu"

txteditmirrorlist="Edit mirrorlist"
txtinstallarchlinux="Install Arch Linux"
txtconfigarchlinux="Config Arch Linux"

txtsethostname="Set Computer Name"
txtsetfont="Set Font"
txtsetlocale="Set Locale"
txtsettime="Set Time"
txtsetrootpassword="Set root password"

txtuseutcclock="Use UTC hardware clock ?"

txtbootloader="Bootloader"
txtbootloadermenu="Choose your bootloader"

txtefibootmgr="efibootmgr is required for EFI computers."

txtbootloadergrubmenu="Grub Install Menu"
txtrungrubmakeconfig="Run grub-mkconfig ?"
txtgrubluksdetected="Encrypted root partion !\n\nAdd cryptdevice= to GRUB_CMDLINE_LINUX in /etc/default/grub ?"

txtbootloadersyslinuxmenu="Syslinux Install Menu"
txtsyslinuxaddefibootmgr="EFI install require efibootmgr"
txtsyslinuxaddgptfdisk="GPT disk require gptfdisk"
txtsyslinuxaddmtools="FAT boot part require mtools"

txtbootloaderrefindmenu="rEFInd Install Menu"

txtoptional="Optional"
txtrecommandeasyinst="Recommanded for easy install"
txtset="Set %1"
txtgenerate="Generate %1"
txtedit="Edit %1"
txtinstall="Install %1"
txtenable="Enable %1"


txtarchdidesc="Full desktop install script"
txtinstallarchdi="Arch Linux Desktop Install (archdi) is a second script who can help you to install a full workstation.\n\nYou can just launch the script or install it. Choose in the next menu.\n\nArch Linux Desktop Install as two dependencies : wget and libnewt.\n\npacstrap wget libnewt ?"
txtarchdiinstallandlaunch="Install and run archdi"
txtarchdiinstall="Install archdi"
txtarchdilaunch="Launch archdi"
